apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-recommendation
  name: mongodb-recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-recommendation
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-recommendation
    spec:
      nodeName: h2.hotel.meshbench-pg0.clemson.cloudlab.us
      containers:
        - image: mongo:4.4.6
          name: hotel-reserv-recommendation-mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m
          volumeMounts:
            - mountPath: /data/db
              name: recommendation
      hostname: recommendation-db
      restartPolicy: Always
      volumes:
        - name: recommendation
          persistentVolumeClaim:
            claimName: recommendation-pvc
status: {}
