apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-rate
  name: mongodb-rate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-rate
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/inject: 'false'
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-rate
    spec:
      containers:
      - image: mongo:4.4.6
        name: hotel-reserv-rate-mongo
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        volumeMounts:
        - mountPath: /data/db
          name: rate
      nodeName: h3.hotelbench.meshbench-pg0.clemson.cloudlab.us
      restartPolicy: Always
      volumes:
      - name: rate
        persistentVolumeClaim:
          claimName: rate-pvc
status: {}
