apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-reservation
  name: mongodb-reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-reservation
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-reservation
    spec:
      containers:
        - image: mongo:4.4.6
          name: hotel-reserv-reservation-mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m
          volumeMounts:
            - mountPath: /data/db
              name: reservation
      hostname: reservation-db
      restartPolicy: Always
      volumes:
        - name: reservation
          persistentVolumeClaim:
            claimName: reservation-pvc
status: {}
