apiVersion: v1
kind: Service
metadata:
  name: webdis-service
spec:
  clusterIP: 10.96.99.99
  ports:
  - port: 7379
    targetPort: 7379
    name: http-redis
  selector:
    app: webdis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdis-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdis
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: webdis
    spec:
      containers:
      - name: webdis
        image: nicolas/webdis
        ports:
        - containerPort: 7379
